server:
  port: 8081
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://47.98.178.84:3306/van_distributed
    username: van_distributed
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.98.178.84
    port: 6379
    password: password
    timeout: 2000
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.van.redisson.lock.entity